/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_andrescruz;

/**
 *
 * @author MBanegas
 */
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class Lab5_AndresCruz extends javax.swing.JFrame {

    ArrayList<Empresa> lista = new ArrayList();

    /**
     * Creates new form Lab5_AndresCruz
     */
    public Lab5_AndresCruz() {
        initComponents();
        dc_fundacion.setDate(new Date());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_empresa = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        tf_nombreempresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dc_fundacion = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_ubicacion = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        tf_idsucursal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_pin = new javax.swing.JTextField();
        jb_guardarempresa = new javax.swing.JButton();
        jd_menuempresa = new javax.swing.JDialog();
        nombrelabel = new javax.swing.JLabel();
        idlabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_empresa = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_empleados = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jd_empleado = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        tf_nombreempleado = new javax.swing.JTextField();
        dc_nacimiento = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_correo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cb_cargo = new javax.swing.JComboBox<>();
        jb_crear = new javax.swing.JButton();
        popupempleados = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        VerDetalles = new javax.swing.JMenuItem();
        Contratar = new javax.swing.JMenuItem();
        popupinfo = new javax.swing.JPopupMenu();
        Informacion = new javax.swing.JMenuItem();
        modificarempleado = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        tf_nombreempleado1 = new javax.swing.JTextField();
        dc_nacimiento1 = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_correo1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cb_cargo1 = new javax.swing.JComboBox<>();
        jb_crear1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        pf_contra = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jb_crearempresa = new javax.swing.JButton();
        jb_entrar = new javax.swing.JButton();

        jLabel4.setText("Nombre: ");

        jLabel5.setText("Fecha de Fundacion: ");

        jLabel6.setText("Tipo de Empresa:");

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Micro", "Mediana", "Gran" }));

        jLabel7.setText("Ubicacion: ");

        ta_ubicacion.setColumns(20);
        ta_ubicacion.setRows(5);
        jScrollPane1.setViewportView(ta_ubicacion);

        jLabel8.setText("ID de la sucursal:");

        jLabel9.setText("Contraseña:");

        jb_guardarempresa.setText("Guardar");
        jb_guardarempresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarempresaMouseClicked(evt);
            }
        });
        jb_guardarempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarempresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_empresaLayout = new javax.swing.GroupLayout(jd_empresa.getContentPane());
        jd_empresa.getContentPane().setLayout(jd_empresaLayout);
        jd_empresaLayout.setHorizontalGroup(
            jd_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_empresaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jd_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_empresaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_empresaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_nombreempresa))
                    .addGroup(jd_empresaLayout.createSequentialGroup()
                        .addGroup(jd_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jd_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dc_fundacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jd_empresaLayout.createSequentialGroup()
                        .addGroup(jd_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_idsucursal)
                            .addComponent(tf_pin))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_empresaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_guardarempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jd_empresaLayout.setVerticalGroup(
            jd_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_empresaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jd_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nombreempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dc_fundacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jd_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_idsucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_guardarempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        nombrelabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nombrelabel.setText("jLabel10");

        idlabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        idlabel.setText("jLabel11");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jt_empresa.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_empresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_empresaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_empresa);

        jButton1.setText("Crear Empleado");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel10.setText("Lista Empleados: ");

        jl_empleados.setModel(new DefaultListModel());
        jl_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_empleadosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jl_empleados);

        jButton2.setText("Log Out");

        javax.swing.GroupLayout jd_menuempresaLayout = new javax.swing.GroupLayout(jd_menuempresa.getContentPane());
        jd_menuempresa.getContentPane().setLayout(jd_menuempresaLayout);
        jd_menuempresaLayout.setHorizontalGroup(
            jd_menuempresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuempresaLayout.createSequentialGroup()
                .addGroup(jd_menuempresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_menuempresaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(nombrelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_menuempresaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jd_menuempresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_menuempresaLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(jd_menuempresaLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_menuempresaLayout.setVerticalGroup(
            jd_menuempresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuempresaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jd_menuempresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombrelabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jd_menuempresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_menuempresaLayout.createSequentialGroup()
                        .addGroup(jd_menuempresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel11.setText("Nombre: ");

        jLabel12.setText("Nacimiento:");

        jLabel13.setText("Correo:");

        jLabel14.setText("Cargo:");

        cb_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniero", "Medico", "Estudiante", "Licenciado", "Maestro" }));

        jb_crear.setText("Crear Empleado");
        jb_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_empleadoLayout = new javax.swing.GroupLayout(jd_empleado.getContentPane());
        jd_empleado.getContentPane().setLayout(jd_empleadoLayout);
        jd_empleadoLayout.setHorizontalGroup(
            jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_empleadoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_crear)
                    .addGroup(jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dc_nacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(tf_nombreempleado)
                        .addComponent(tf_correo))
                    .addComponent(cb_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jd_empleadoLayout.setVerticalGroup(
            jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_empleadoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_nombreempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dc_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cb_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jb_crear)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        popupempleados.add(Modificar);

        Eliminar.setText("Eliminar");
        popupempleados.add(Eliminar);

        VerDetalles.setText("Ver Detalles");
        popupempleados.add(VerDetalles);

        Contratar.setText("Contratar");
        popupempleados.add(Contratar);

        Informacion.setText("Informacion");
        popupinfo.add(Informacion);

        jLabel15.setText("Nombre: ");

        jLabel16.setText("Nacimiento:");

        jLabel17.setText("Correo:");

        jLabel18.setText("Cargo:");

        cb_cargo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniero", "Medico", "Estudiante", "Licenciado", "Maestro" }));

        jb_crear1.setText("Modificar");
        jb_crear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crear1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout modificarempleadoLayout = new javax.swing.GroupLayout(modificarempleado.getContentPane());
        modificarempleado.getContentPane().setLayout(modificarempleadoLayout);
        modificarempleadoLayout.setHorizontalGroup(
            modificarempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarempleadoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(modificarempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificarempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_crear1)
                    .addGroup(modificarempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dc_nacimiento1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(tf_nombreempleado1)
                        .addComponent(tf_correo1))
                    .addComponent(cb_cargo1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        modificarempleadoLayout.setVerticalGroup(
            modificarempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarempleadoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(modificarempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_nombreempleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modificarempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dc_nacimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(modificarempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(tf_correo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modificarempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cb_cargo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jb_crear1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("ID de la empresa: ");

        jLabel3.setText("Contraseña:");

        jb_crearempresa.setText("Crear Empresa");
        jb_crearempresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearempresaMouseClicked(evt);
            }
        });

        jb_entrar.setText("Iniciar Sesion");
        jb_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_entrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_entrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_crearempresa))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pf_contra)
                            .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_crearempresa)
                    .addComponent(jb_entrar))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crearempresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearempresaMouseClicked
        // TODO add your handling code here:
        jd_empresa.setModal(true);
        jd_empresa.pack();
        jd_empresa.setLocationRelativeTo(this);
        jd_empresa.setVisible(true);
    }//GEN-LAST:event_jb_crearempresaMouseClicked

    private void jb_guardarempresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarempresaMouseClicked
        // TODO add your handling code here:
        String Nombre;
        double capital = 0;
        Date fundacion;
        String tipo="";
        String ubicacion;
        String id_sucursal;
        String pin;
        if (tf_pin.getText().isEmpty() || tf_idsucursal.getText().isEmpty() || tf_nombreempresa.getText().isEmpty() || ta_ubicacion.toString().isEmpty()) {
            JOptionPane.showMessageDialog(jd_empresa, "Algunos campos estan vacios!!");
        } else {
            try {
                Nombre = tf_nombreempresa.getText();
                if (cb_tipo.getSelectedItem().toString().equals("Micro")) {
                    capital = 80000;
                    tipo = cb_tipo.getSelectedItem().toString();
                }
                if (cb_tipo.getSelectedItem().toString().equals("Mediana")) {
                    capital = 120000;
                    tipo = cb_tipo.getSelectedItem().toString();
                }
                if (cb_tipo.getSelectedItem().toString().equals("Gran")) {
                    capital = 169000;
                    tipo = cb_tipo.getSelectedItem().toString();
                }
                fundacion = dc_fundacion.getDate();
                ubicacion = ta_ubicacion.getText();
                id_sucursal = tf_idsucursal.getText();
                pin = tf_pin.getText();
                if (nom(Nombre) || idsuc(id_sucursal) || idsucint(id_sucursal)) {
                    if (nom(Nombre)) {
                        JOptionPane.showMessageDialog(jd_empresa, "Ya existe otra empresa con ese nombre!!");
                    }
                    if (idsuc(id_sucursal)) {
                        JOptionPane.showMessageDialog(jd_empresa, "Ya existe otra empresa con ese ID de sucursal!!");
                    }
                    if (idsucint(id_sucursal)) {
                        JOptionPane.showMessageDialog(jd_empresa, "La id de sucursal debe ser siempre numerico!!");
                    }
                } else {
                    tf_idsucursal.setText("");
                    tf_nombreempresa.setText("");
                    tf_pin.setText("");
                    cb_tipo.setSelectedIndex(0);
                    ta_ubicacion.setText("");
                    dc_fundacion.setDate(new Date());                    
                    DefaultTreeModel arbol=(DefaultTreeModel)jt_empresa.getModel();
                    DefaultMutableTreeNode t=new DefaultMutableTreeNode(Nombre);
                    arbol.setRoot(t);                                     
                    lista.add(new Empresa(Nombre, capital, fundacion, tipo, ubicacion, id_sucursal, pin, arbol));
                    JOptionPane.showMessageDialog(jd_empresa, "Se creo la empresa de manera correcta!");
                    jd_empresa.dispose();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(jd_empresa, "Datos ingresados incorrectos!!");
            }

        }
    }//GEN-LAST:event_jb_guardarempresaMouseClicked

    private void jb_guardarempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarempresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_guardarempresaActionPerformed

    private void jb_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearMouseClicked
        // TODO add your handling code here:
        String nombre;
        Date nacimiento;
        String correo;
        String cargo;
        double salario = 0;
        if (tf_nombreempleado.getText().isEmpty() || tf_correo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_empleado, "Algunos campos estan vacios!!");
        } else {
            try {
                nombre = tf_nombreempleado.getText();
                nacimiento = dc_nacimiento.getDate();
                correo = tf_correo.getText();
                cargo = cb_cargo.getSelectedItem().toString();
                switch (cargo) {
                    case "Ingeniero":
                        salario = 22000;
                        break;
                    case "Medico":
                        salario = 18000;
                        break;
                    case "Estudiante":
                        salario = 7600;
                        break;
                    case "Licenciado":
                        salario = 12000;
                        break;
                    case "Maestro":
                        salario = 2000;
                        break;
                }
                DefaultListModel modelo = (DefaultListModel) jl_empleados.getModel();
                modelo.addElement(new Empleado(nombre, nacimiento, correo, cargo, salario));
                tf_nombreempleado.setText("");
                dc_nacimiento.setDate(new Date());
                tf_correo.setText("");
                cb_cargo.setSelectedIndex(0);
                JOptionPane.showMessageDialog(jd_empresa, "Se creo el empleado de manera correcta!");
                jd_empleado.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(jd_empresa, "Datos ingresados incorrectos!!");
            }

        }
    }//GEN-LAST:event_jb_crearMouseClicked

    private void jb_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_entrarMouseClicked
        // TODO add your handling code here:
        boolean id = false;
        int index = 0;
        for (int i = 0; i < lista.size(); i++) {
            if (tf_id.getText().equals(lista.get(i).getId_sucursal())) {
                index = i;
                id = true;
                break;
            }
        }

        if (id && pf_contra.getText().equals(lista.get(index).getPin())) {
            seleccionado=lista.get(index);
            jt_empresa.setModel(seleccionado.getArbol());
            nombrelabel.setText(seleccionado.getNombre());
            idlabel.setText(seleccionado.getId_sucursal());
            tf_id.setText("");
            pf_contra.setText("");
            jd_menuempresa.setModal(true);
            jd_menuempresa.pack();
            jd_menuempresa.setLocationRelativeTo(this);
            jd_menuempresa.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No existe el usuario o la contraseña!");
        }

    }//GEN-LAST:event_jb_entrarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jd_empleado.setModal(true);
        jd_empleado.pack();
        jd_empleado.setLocationRelativeTo(jd_menuempresa);
        jd_empleado.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jl_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_empleadosMouseClicked
        // TODO add your handling code here:
        if (jl_empleados.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                popupempleados.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_empleadosMouseClicked

    private void jt_empresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_empresaMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row=jt_empresa.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_empresa.setSelectionRow(row);
            Object v1=jt_empresa.getSelectionPath().getLastPathComponent();
            nodo_seleccionado=(DefaultMutableTreeNode)v1;            
            popupinfo.show(evt.getComponent(), evt.getX(), evt.getY());            
        }
    }//GEN-LAST:event_jt_empresaMouseClicked

    private void jb_crear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crear1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jb_crear1MouseClicked

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        if (jl_empleados.getSelectedIndex()>=0) {
            DefaultListModel modelo=(DefaultListModel)jl_empleados.getModel();
            persona_seleccionada=(Empleado)modelo.getElementAt(jl_empleados.getSelectedIndex());
            modificarempleado.setModal(true);
            modificarempleado.pack();
            modificarempleado.setLocationRelativeTo(jd_menuempresa);
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private boolean nom(String nombre) {
        for (int i = 0; i < lista.size(); i++) {
            if (nombre.equals(lista.get(i).getNombre())) {
                return true;
            }
        }
        return false;
    }

    private boolean idsuc(String nombre) {
        for (int i = 0; i < lista.size(); i++) {
            if (nombre.equals(lista.get(i).getId_sucursal())) {
                return true;
            }
        }
        return false;
    }

    private boolean idsucint(String nombre) {
        for (int i = 0; i < nombre.length(); i++) {
            if (Character.isDigit(nombre.charAt(i))) {

            } else {
                return true;
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab5_AndresCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab5_AndresCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab5_AndresCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab5_AndresCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab5_AndresCruz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Contratar;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Informacion;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JMenuItem VerDetalles;
    private javax.swing.JComboBox<String> cb_cargo;
    private javax.swing.JComboBox<String> cb_cargo1;
    private javax.swing.JComboBox<String> cb_tipo;
    private com.toedter.calendar.JDateChooser dc_fundacion;
    private com.toedter.calendar.JDateChooser dc_nacimiento;
    private com.toedter.calendar.JDateChooser dc_nacimiento1;
    private javax.swing.JLabel idlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_crear;
    private javax.swing.JButton jb_crear1;
    private javax.swing.JButton jb_crearempresa;
    private javax.swing.JButton jb_entrar;
    private javax.swing.JButton jb_guardarempresa;
    private javax.swing.JDialog jd_empleado;
    private javax.swing.JDialog jd_empresa;
    private javax.swing.JDialog jd_menuempresa;
    private javax.swing.JList<String> jl_empleados;
    private javax.swing.JTree jt_empresa;
    private javax.swing.JDialog modificarempleado;
    private javax.swing.JLabel nombrelabel;
    private javax.swing.JPasswordField pf_contra;
    private javax.swing.JPopupMenu popupempleados;
    private javax.swing.JPopupMenu popupinfo;
    private javax.swing.JTextArea ta_ubicacion;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_correo1;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_idsucursal;
    private javax.swing.JTextField tf_nombreempleado;
    private javax.swing.JTextField tf_nombreempleado1;
    private javax.swing.JTextField tf_nombreempresa;
    private javax.swing.JTextField tf_pin;
    // End of variables declaration//GEN-END:variables
Empresa seleccionado;
DefaultMutableTreeNode nodo_seleccionado;
    Empleado persona_seleccionada;
}
